### ISSUE TITLE
Maintainance

### ISSUE THREAD

**Issue by asphalter** [DerEnderKeks/docker-murmur#4]
Hi, I noticed that the project isn't maintained anymore since the 2021.

Do you guys think that you'll update the server to 1.4.x or this docker project has reached a deadline for you?

Thanks

**Comment by DerEnderKeks** [comment]
I honestly forgot that I even made this image. I'm currently just using the [official image](https://github.com/mumble-voip/mumble-docker).

It seems like Mumble no longer provides compiled binaries for Murmur, so this image won't work, until someone adds the steps required to compile Murmur. I'll archive this project, feel free to fork it though.
